In [2]:
import numpy as np
import time

In [4]:
a=[1,2,3,4,5,6,7,8,9,10]*1000000
start = time.time()
for i in range(len(a)):
    a[i]=a[i]*2

print("\ntime taken from list :",time.time() - start)


time taken from list : 1.0524368286132812


In [5]:
a=[1,2,3,4,5,6,7,8,9,10]*1000000
b=np.array(a)
start = time.time()
nem_b = b*2
print("\ntime taken from list :",time.time() - start)


time taken from list : 0.018184185028076172


In [6]:
import sys

In [7]:
a=[1,2,3,4,5,6]
b=np.array(a) 
print("List size :",sys.getsizeof(a))
print("Array size :",b.nbytes)

List size : 104
Array size : 48


In [8]:
a=[1,True,"yaswanth",3468,3.4]
print(type(a))
print(a)
b=np.array(a)
print(b)

<class 'list'>
[1, True, 'yaswanth', 3468, 3.4]
['1' 'True' 'yaswanth' '3468' '3.4']


# dimensions and shapes

In [9]:
arr= np.array([1,2,3,4,5])

In [10]:
arr.ndim

1

In [11]:
arr= np.array(567)
arr.ndim

0

In [19]:
a= np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
    ])
a.ndim

2

In [20]:
a.shape

(2, 5)

## creating numpy array

In [21]:
range = np.arange(1,10)
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
range = np.arange(1,10,2)
range

array([1, 3, 5, 7, 9])

In [23]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [62]:
arr = np.logspace(1,3,3)# 10^1,10^2,10^3___>3 points if we write 2 it gives 2 points
arr

array([  10.,  100., 1000.])

In [27]:
# np.zeros -> array full of zeros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [28]:
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
arr = np.zeros([2,3,5])
arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [33]:
arr = np.ones([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [37]:
arr = np.ones(5,dtype = int)
arr

array([1, 1, 1, 1, 1])

In [39]:
arr = np.full(5,7)
arr

array([7, 7, 7, 7, 7])

In [44]:
arr = np.full([2,3],7)# [row,column],default value
arr

array([[7, 7, 7],
       [7, 7, 7]])

In [50]:
arr = np.empty([2,3]) # uninitialized array -> creates an array without setting any values
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

## creating random numpy arrays

In [53]:
arr= np.random.rand(10) # ->random flotes(0 to 1)
arr

array([0.86333336, 0.9027119 , 0.52814601, 0.88335532, 0.34710284,
       0.2776427 , 0.92947348, 0.75038506, 0.00648216, 0.8402711 ])

In [55]:
arr= np.random.rand(2,3) 
arr

array([[0.59199771, 0.6466584 , 0.73640433],
       [0.20274364, 0.46845919, 0.81842104]])

In [56]:
arr= np.random.randn(2,3)
arr

array([[ 1.13602902, -0.56036478,  1.98431363],
       [ 0.84344987,  0.12313405,  1.69304187]])

In [58]:
arr= np.random.randint(1,100)
arr

98

In [60]:
arr= np.random.randint(1,100, size=(2,3))
arr

array([[31, 85, 19],
       [63, 21,  7]], dtype=int32)

## numpy datatype and type casting

In [63]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
print(type(arr))

<class 'numpy.ndarray'>


In [68]:
lst= ["yaswanth",1,2,5.6]
arr = np.array(lst)
arr

array(['yaswanth', '1', '2', '5.6'], dtype='<U32')

In [72]:
arr = np.array(list(lst))
arr

array(['yaswanth', '1', '2', '5.6'], dtype='<U32')

In [74]:
arr = np.array([1,2,3,4,5,6,7,8])
arr.dtype

dtype('int64')

In [75]:
arr = np.array([1,2,3,4,5.6,6,7,8])
arr.dtype

dtype('float64')

In [77]:
arr = np.array([1,2,3,4,5,6,7,8], dtype=np.float32)
arr.dtype

dtype('float32')

In [79]:
#type casting -> astype()
arr = np.array([1,2,3,4,5,6,7,8])
arr.dtype

dtype('int64')

In [81]:
newarr = arr.astype(np.float64)
newarr.dtype

dtype('float64')

In [82]:
newarr

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [83]:
arr = newarr.astype(np.int64)
arr.dtype

dtype('int64')

In [84]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

## type casting errors

In [5]:
import numpy as np
arr =np.array(["1","2","hello"])
arr2 = arr.astype(np.int64)
arr2

ValueError: invalid literal for int() with base 10: np.str_('hello')

## numpy array attributes

In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr.ndim

2

In [10]:
arr.shape

(2, 4)

In [11]:
arr.size

8

In [12]:
arr.itemsize

8

## array reshaping -> reshape,ravel,flatten

In [13]:
arr=np.array([1,2,3,4,5,6,7,8])
reshape=arr.reshape(2,4)
print(reshape)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
reshape2=reshape.reshape(4,2)
print(reshape2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
# ravel -> convert 1D array
ravel = reshape2.ravel()
ravel

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
#flatten -> to 1D array
# -> returns a copy of the array

flat = reshape2.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
ravel[0]=100
print(ravel)
print(reshape2)

[100   2   3   4   5   6   7   8]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [21]:
flat[0] = 30
print(flat)
print(reshape2)

[30  2  3  4  5  6  7  8]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


## arithmetic operations on arrays

In [22]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [23]:
#add
print(a+b)

[ 6  8 10 12]


In [26]:
print(a-b)

[-4 -4 -4 -4]


In [27]:
#sub
print(abs(a-b))

[4 4 4 4]


In [30]:
 #div
print(a/b)

[0.2        0.33333333 0.42857143 0.5       ]


In [31]:
#mul
print(a*b)

[ 5 12 21 32]


In [33]:
#div floor
print(a//b)

[0 0 0 0]


In [35]:
# modules
print(b%a)

[0 0 1 0]


In [36]:
# exponence
print(a**b)

[    1    64  2187 65536]


## universal function -> ufuncs

In [38]:
arr = np.array([1,4,6,8,9])

In [40]:
#squart
print(np.sqrt(arr))

[1.         2.         2.44948974 2.82842712 3.        ]


In [41]:
#exponentioal -> np.exp -> e^x 
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [43]:
# sin function
angles = np.array([0,np.pi, np.pi/2])

In [44]:
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


## indexing and slicing

In [45]:
a= [1,2,3,4,5,6]

In [46]:
a[-1:-4]

[]

In [47]:
a[-1:-4:-1]

[6, 5, 4]

In [48]:
a[::2]

[1, 3, 5]

In [49]:
arr=np.array([10,20,30,40,50])
arr[::2]

array([10, 30, 50])

In [50]:
print(arr[-1])

50


## multidimensional slicing

In [2]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(matrix[0:2, 0:3])

[[1 2 3]
 [4 5 6]]


In [5]:
print(matrix[1:,1: ])

[[5 6]
 [8 9]]


In [6]:
arr=np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(arr,ind))

[10 30]


In [7]:
arr=np.array([[1,2],[3,4]])

In [8]:
for i in np.nditer(arr):
    print(i)

1
2
3
4


In [9]:
for i in np.nditer(arr):
    print(i, end=" ")

1 2 3 4 

In [11]:
# ndenumerate() -> prints both index and values
for ind,i in np.ndenumerate(arr):
    print(ind,i)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


## views and copies

In [12]:
arr= np.array([1,2,3,4,5,6])
view = arr[1:3]
view

array([2, 3])

In [13]:
view[0] = 200
view

array([200,   3])

In [14]:
arr

array([  1, 200,   3,   4,   5,   6])

In [15]:
# copy
copy= arr[1:3].copy()
copy

array([200,   3])

In [16]:
copy[0]=2
copy

array([2, 3])

In [17]:
arr

array([  1, 200,   3,   4,   5,   6])

## transpose of a matrix

In [18]:
arr= np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [19]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [20]:
# swapaxes ->swap 2 specific axes in a matrix.
arr= np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [22]:
swap = np.swapaxes(arr, 0,1)
swap.shape

(2, 1, 2)