In [1]:
import numpy as np

In [2]:
big_list = list(range(100000))
big_array= np.arange(100000)

In [3]:
%timeit [x**2 for x in big_list]

11.1 ms ± 142 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit big_array ** 2

98.6 μs ± 1.9 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [5]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [7]:
b=np.array([[1,2,3,4],[6,7,8,9]])
print(b)

[[1 2 3 4]
 [6 7 8 9]]


In [8]:
a=np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [9]:
zero =np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [12]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [13]:
print(np.eye(3)) #identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
rng = np.random.default_rng(42)
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [15]:
print(rng.integers(1,10,size=(3,3))) #uniform

[[7 7 7]
 [8 5 2]
 [8 5 5]]
